services:
  api:
    build: .
    ports:
      - '127.0.0.1:55556:55556'
    environment:
      PORT: '55556'
      JWT_SECRET: '${JWT_SECRET}'
      FRONTEND_URL: '${FRONTEND_URL}'
      DB_HOST: 'yesang-db'
      DB_PORT: '3306'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      DB_LOGGING: '${DB_LOGGING:-false}'
      DB_SYNCHRONIZE: '${DB_SYNCHRONIZE:-false}'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID:-}'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET:-}'
      GOOGLE_CALLBACK_URL: '${GOOGLE_CALLBACK_URL:-}'
      KAKAO_CLIENT_ID: '${KAKAO_CLIENT_ID:-}'
      KAKAO_CALLBACK_URL: '${KAKAO_CALLBACK_URL:-}'
      APPLE_CLIENT_ID: '${APPLE_CLIENT_ID:-}'
      APPLE_BUNDLE_ID: '${APPLE_BUNDLE_ID:-}'
      APPLE_TEAM_ID: '${APPLE_TEAM_ID:-}'
      APPLE_KEY_ID: '${APPLE_KEY_ID:-}'
      APPLE_PRIVATE_KEY_PATH: '${APPLE_PRIVATE_KEY_PATH:-}'
      APPLE_CALLBACK_URL: '${APPLE_CALLBACK_URL:-}'
    volumes:
      - ./AuthKey_FY76TKJW2W.p8:/app/AuthKey_48CZBZF894.p8.p8:ro
    depends_on:
      - yesang-db
    restart: unless-stopped

  yesang-db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}' # yesang
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - yesang_db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  yesang_db_data:
